### ISSUE TITLE
Issue on MAC OS

### ISSUE THREAD

**Issue by pythonblast** [pedromargolles/citrix_copy_clipboard_to_remote#1]
I've installed all necessary packages below, but I getting the following error.

- pyperclip
- pynput
- pyparsing

**Error that I receive:** 
```
sh-3.2# python3 copy.py 
Traceback (most recent call last):
  File "copy.py", line 1, in <module>
    from pynput.keyboard import Key, Controller
  File "/Library/Python/3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/Library/Python/3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/Library/Python/3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: The 'pyparsing' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

Try one of the following resolutions:

 * Please make sure that you have Python bindings for the system frameworks installed
sh-3.2# 

```

**Comment by pedromargolles** [comment]
You can try to rename your copy.py file to original copy_citrix.py as stated in these threads:

https://stackoverflow.com/questions/62511015/importerror-the-pyparsing-package-is-required

https://ethereum.stackexchange.com/questions/34793/importerror-while-trying-to-use-web3-py

Lets see if that works.

**Comment by pythonblast** [comment]
AWESOME IT WORKED!!! You the man!

**Comment by pedromargolles** [comment]
Glad to hear that! Then I close this thread. Don't forget to give a star to this project so more people can benefit :)
